hack/hack/hack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hackstar.urls')),
]

hack/hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hackstar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hack/hackstar/models.py
from django.db import models

# Create your models here.


class cleanliness_model(models.Model):
    objects = None
    name = models.CharField(default='', max_length=100)
    pnr = models.CharField(default='', max_length=100)
    building_name = models.CharField(max_length=100, default='')
    class_no = models.CharField(default='', max_length=100)
    description = models.CharField(default='', max_length=100)
    cleaned = models.CharField(default='', max_length=100)

    def __str__(self):
        return self.class_no


class contact_model(models.Model):
    name = models.CharField(default='', max_length=100)
    email = models.EmailField(default='', max_length=100)
    message = models.CharField(default='', max_length=100)

    def __str__(self):
        return self.name


class lost_found_model(models.Model):
    name = models.CharField(default='', max_length=100)
    pnr = models.CharField(default='', max_length=100)
    building_name = models.CharField(max_length=100, default='')
    class_no = models.CharField(default='', max_length=100)
    description = models.CharField(default='', max_length=100)
    item = models.CharField(default='', max_length=100)
    image = models.FileField(upload_to='images/', null=True, verbose_name="", default='')
    date_time= models.DateField(default='')
    found = models.CharField(default='', max_length=100)

    def __str__(self):
        return self.class_no


class UserDetails(models.Model):
    objects = None
    name = models.CharField(max_length=100)
    prn_number = models.IntegerField(default=0)
    password = models.CharField(max_length=100)
    address = models.CharField(max_length=150)
    contact = models.IntegerField(default=0)
    email = models.EmailField(default=True, primary_key=True)
    role = models.CharField(max_length=20, default="User")

    def __str__(self):
        return self.role


# Create your models here.
class Foods(models.Model):
    canteen_name = models.CharField(max_length=100,default="")
    image = models.ImageField(upload_to="pics")
    categeory = models.CharField(max_length=50, default="")
    name = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    def _str_(self):
        return self.name


class Order(models.Model):
    items_json = models.CharField(max_length=1000, default="")
    name = models.CharField(max_length=50, default="")
    time = models.CharField(max_length=20, default="")
    phone = models.IntegerField(default=0)
    tprice = models.CharField(max_length=20, default='')
    status = models.CharField(max_length=20, default='')
    def _str_(self):
        return self.tprice


class EventDetails(models.Model):
    name = models.CharField(max_length=100)
    prn_number = models.IntegerField(default=0, primary_key=True)
    event_name = models.CharField(max_length=100)
    event_dest = models.CharField(max_length=100)
    max_crowd = models.IntegerField(default=0)
    duration = models.DateTimeField()

    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=100,default='')
    desc = models.CharField(max_length=1000,default='')
    date = models.CharField(max_length=20,default='')
    register = models.IntegerField(max_length=100,default=0)
    def __str__(self):
        return self.name
    
class Eregister(models.Model):
    name = models.CharField(max_length=100, default='')
    event_id= models.IntegerField(default=0)
    prn = models.CharField(max_length=100, default='')
    course = models.CharField(max_length=100, default='')
    year = models.CharField(max_length=100, default='')
    phone = models.IntegerField(default=0)

hack/templates/cleanliness.html
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>University Helping Hand Services</title>
</head>

<body style="background-image: url('{% static 'images/cleanlinessbg.jpg'%}'); background-repeat: no-repeat; background-size: cover;">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><img src="{% static 'images/logo1.png'%}" height="50%" width="70%"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Home'%}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">{{ request.session.email }} <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Services
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'canteen' %}">Canteen</a>
                        <a class="dropdown-item" href="{% url 'cleanliness' %}">Cleanliness</a>
                        <a class="dropdown-item" href="{% url 'lostfound' %}">Lost & Found</a>
                        <a class="dropdown-item" href="{% url 'event' %}">Event Management</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="viewcl">View <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="/" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button> &nbsp; &nbsp;
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Log Out</button>
            </form>
        </div>
    </nav>



<div class="container" style="width: 60%; padding: 50px; box-shadow: 5px 5px 5px 5px black; background-color:rgba(239,239,239,0.9);border-radius:25px; ">
    <h1
            style="font-size: 30px; text-align: center; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
        Cleanliness Complaints</h1>
    <p style="text-align: center;"><i>"Cleanliness is a state of purity, clarity, and precision. So keep your
        surrounding clean."</i></p>
    <br>
    <form  method="POST" >
        {% csrf_token %}
        <div class="form-group">
            <label >Name:</label>
            {{form.name}}
        </div>

        <div class="form-group">
            <label >PRN Number:</label>
            {{form.pnr}}

            <!--                <input type="number" class="form-control" id="id_pnr" placeholder="10621xxxxx">-->
        </div>

        <div class="form-group">
            <label >Building Name:</label>
            <!--                                <input type="text" class="form-control" id="id_building_name" placeholder="10621xxxxx">-->
            {{form.building_name}}

            <!--                <select class="form-control" id="BuildingName">-->
            <!--                    <option>&#45;&#45;Select&#45;&#45;</option>-->
            <!--                    <option>MIT-SOM</option>-->
            <!--                    <option>MIT-SOB</option>-->
            <!--                    <option>MIT-Pharmacy</option>-->
            <!--                    <option>MIT-Engineering</option>-->
            <!--                </select>-->
        </div>

        <div class="form-group">
            <label>Classroom Number:</label>
            <!--                <input type="number" class="form-control" id="id_class_no" placeholder="10621xxxxx">-->
            {{form.class_no}}

        </div>



        <div class="form-group">
            <label >Description:</label>
            <!--                <textarea class="form-control" id="id_description" rows="3"></textarea>-->
            {{form.description}}

        </div>

        <div class="form-group">
            <label >Is Cleaned:</label>
            {{form.cleaned}}

        </div>


        <div class="p-2 w-full">
            <button
                    class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Add
                Complaint</button>
        </div>

    </form>
</div>







<footer class="text-gray-700 body-font" style="background-color: black;">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
            <a class="navbar-brand" href="#"><img src="{% static 'images/logo1.png'%}" height="50%" width="70%"></a>
        </a>
        <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">©
            2020 University Helping Hand

        </p>
        <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
                <a class="text-gray-500">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                         class="w-5 h-5" viewBox="0 0 24 24">
                        <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                    </svg>
                </a>
                <a class="ml-3 text-gray-500">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                         class="w-5 h-5" viewBox="0 0 24 24">
                        <path
                                d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z">
                        </path>
                    </svg>
                </a>
                <a class="ml-3 text-gray-500">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                         stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                        <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                        <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                    </svg>
                </a>
                <a class="ml-3 text-gray-500">
                    <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                         stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                        <path stroke="none"
                              d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z">
                        </path>
                        <circle cx="4" cy="4" r="2" stroke="none"></circle>
                    </svg>
                </a>
            </span>
    </div>
</footer>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>

</html>

hack/templates/update_lost.html
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>University Helping Hand Services</title>
</head>

<body style="background-image: url('{% static 'images/cleanlinessbg.jpg'%}'); background-repeat: no-repeat; background-size: cover;">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><img src="{% static 'images/logo1.png'%}" height="50%" width="70%"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Home'%}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">{{ request.session.email }} <span class="sr-only">(current)</span></a>
                </li>
               
            </ul>
            <form class="form-inline my-2 my-lg-0" action="/" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button> &nbsp; &nbsp;
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Log Out</button>
            </form>
        </div>
    </nav>

<div class="container" style="width: 60%; padding: 50px; box-shadow: 5px 5px 5px 5px black; background-color:rgba(239,239,239,0.9);border-radius:25px; ">
    <h1
            style="font-size: 30px; text-align: center; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
        Lost & Found Issues</h1>
    <p style="text-align: center;"><i>"Nothing is ever lost. Nothing can't be found"</i></p>

    <br>
    <form  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label >Name:</label>
            <input type="text" class="form-control" id="id_name" name="name"  value="{{form2.name}}"/>
        </div>
        <div class="form-group">
            <label >PRN Number:</label>
            <input type="number" class="form-control" id="id_pnr" name= "pnr"  value="{{form2.pnr}}"/>
        </div>
        <div class="form-group">
            <label >Building Name:</label>
            <input type="text" class="form-control" name= "building_name" id="id_building_name" value="{{form2.building_name}}"/>
        </div>
        <div class="form-group">
            <label>Classroom Number:</label>
            <input type="number" class="form-control" id="id_class_no" name="class_no" value="{{form2.class_no}}"/>
        </div>
        <div class="form-group">
            <label >Item Name:</label>
            <input type="text" class="form-control" id="id_item" name= "item" value="{{form2.item}}"/>
        </div>
        <div class="form-group">
            <label >Lost On:</label>
            <input type="date" class="form-control" id="id_date_time" name= "date_time" value="{{form2.date_time}}"/>
        </div>
        <div class="form-group">
            <label >Description:</label>
            <input type="text" class="form-control" id="id_description" name= "description" value="{{form2.description}}"/>
        </div>
        <div class="form-group">
            <label >Photo of the Item :</label>
            <input type="file" class="form-control" id="id_image" name= "image" value="{{form2.image}}"/>
        </div>
        <div class="form-group">
                <label >Is Found:</label>

                <input type="text" class="form-control" id="id_found" name= "found"  value="{{form2.found}}"/>
            </div>
        <div class="p-2 w-full">
            <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Update</button>
        </div>
    </form>
</div>







<footer class="text-gray-700 body-font" style="background-color: black;">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
            <a class="navbar-brand" href="#"><img src="{% static 'images/logo1.png'%}" height="50%" width="70%"></a>
        </a>
        <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">©
            2020 University Helping Hand

        </p>
        <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
                <a class="text-gray-500">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                         class="w-5 h-5" viewBox="0 0 24 24">
                        <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                    </svg>
                </a>
                <a class="ml-3 text-gray-500">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                         class="w-5 h-5" viewBox="0 0 24 24">
                        <path
                                d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z">
                        </path>
                    </svg>
                </a>
                <a class="ml-3 text-gray-500">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                         stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                        <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                        <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                    </svg>
                </a>
                <a class="ml-3 text-gray-500">
                    <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                         stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                        <path stroke="none"
                              d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z">
                        </path>
                        <circle cx="4" cy="4" r="2" stroke="none"></circle>
                    </svg>
                </a>
            </span>
    </div>
</footer>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>

</html>